services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    container_name: api-gateway

    restart: unless-stopped