spring.application.name=maintenance-service-api-gate-away
server.port=${PORT:8082}


spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.local-case-service-id=true