spring.application.name=api-gateway
server.port=${PORT}

eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
eureka.client.healthcheck.enabled=true
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_URL}

management.endpoints.web.exposure.include=health,info,prometheus,gateway


springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Image Service
springdoc.swagger-ui.urls[1].url=/image-service/api-docs